from .web_search import web_search
from .visit_webpage import visit_webpage
from .load_file import load_file
from .reverse_text import reverse_text
from .analyze_chess import analyze_chess
from .analyze_document import analyze_document
from .classify_food import classify_foods
from .transcript_audio import transcribe_audio
from .execute_code import execute_code
from .analyze_excel import analyze_excel